AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  news-2000 SAM config

Globals:
  Function:
    Timeout: 10
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'www.2000.news'"
    Domain:
      DomainName: api.2000.news
      CertificateArn: arn:aws:acm:us-east-2:663940524453:certificate/a9364e96-df7e-4471-8c2b-fd484e557c7b
      SecurityPolicy: TLS_1_2
      EndpointConfiguration: REGIONAL

Resources:

  Stories:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Stories
      AttributeDefinitions:
        - AttributeName: YearMonthDay
          AttributeType: S
        - AttributeName: Title
          AttributeType: S
      KeySchema:
        - AttributeName: YearMonthDay
          KeyType: HASH
        - AttributeName: Title
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  Words:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Words
      AttributeDefinitions:
        - AttributeName: WordType
          AttributeType: S
        - AttributeName: Word
          AttributeType: S
      KeySchema:
        - AttributeName: WordType
          KeyType: HASH
        - AttributeName: Word
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SubvertedHeadlines:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SubvertedHeadlines
      AttributeDefinitions:
        - AttributeName: YearMonthDay
          AttributeType: S
        - AttributeName: HeadlineId
          AttributeType: S
      KeySchema:
        - AttributeName: YearMonthDay
          KeyType: HASH
        - AttributeName: HeadlineId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  Fetch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Fetch/fetch.fetch
      Runtime: python3.13
      MemorySize: 1024
      Events:
        # 4x/day: 5am, 11am, 3pm, 8pm PT (UTC: 13, 19, 23, 04)
        FetchMorning:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
            Enabled: True
        FetchMidday:
          Type: Schedule
          Properties:
            Schedule: cron(0 19 * * ? *)
            Enabled: True
        FetchAfternoon:
          Type: Schedule
          Properties:
            Schedule: cron(0 23 * * ? *)
            Enabled: True
        FetchEvening:
          Type: Schedule
          Properties:
            Schedule: cron(0 4 * * ? *)
            Enabled: True

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Stories
        - SSMParameterReadPolicy:
            ParameterName: 2000news/*

  Subvert:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Subvert/subvert.subvert
      Runtime: python3.13
      MemorySize: 1024
      Timeout: 120
      Environment:
        Variables:
          BRAINSTORM_PROVIDER: anthropic
          BRAINSTORM_MODEL: claude-opus-4-6
          GENERATE_PROVIDER: anthropic
          GENERATE_MODEL: claude-haiku-4-5
      Events:
       DDBEvent:
         Type: DynamoDB
         Properties:
           Stream: !GetAtt Stories.StreamArn
           StartingPosition: TRIM_HORIZON
           BatchSize: 3
           Enabled: True

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Stories
        - DynamoDBCrudPolicy:
            TableName: !Ref SubvertedHeadlines
        - DynamoDBCrudPolicy:
            TableName: !Ref Words
        - SSMParameterReadPolicy:
            ParameterName: 2000news/*

  Tournament:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Tournament/tournament.tournament
      Runtime: python3.13
      MemorySize: 1024
      Timeout: 900
      Environment:
        Variables:
          TOURNAMENT_PROVIDER: google
          TOURNAMENT_MODEL: gemini-2.5-flash
          TOURNAMENT_FINALS_PROVIDER: anthropic
          TOURNAMENT_FINALS_MODEL: claude-opus-4-6
          TOURNAMENT_FINALS_CUTOFF: 64
      Events:
        HeadlineStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt SubvertedHeadlines.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1000
            MaximumBatchingWindowInSeconds: 300
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SubvertedHeadlines
        - SSMParameterReadPolicy:
            ParameterName: 2000news/*

  Get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Get/get.get
      Runtime: python3.13
      MemorySize: 1024
      Events:
        GetStoriesForTodayApiEvent:
          Type: Api
          Properties:
            Path: /today
            Method: get
        GetStoriesForDayApiEvent:
          Type: Api
          Properties:
            Path: /{day}
            Method: get
        GetHeadlineApiEvent:
          Type: Api
          Properties:
            Path: /{day}/{headline_slug}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Stories
        - DynamoDBReadPolicy:
            TableName: !Ref SubvertedHeadlines
        - DynamoDBCrudPolicy:
            TableName: !Ref Words

Outputs:
  GetStoriesForTodayApi:
    Description: "Custom API Gateway endpoint for prod GetStoriesForToday"
    Value: "https://api.2000.news/today"
  GetStoriesForDayApi:
    Description: "Custom API Gateway endpoint for prod GetStoriesForDay"
    Value: "https://api.2000.news/{day}"
  GetHeadlineApi:
    Description: "Custom API Gateway endpoint for prod GetHeadline"
    Value: "https://api.2000.news/{day}/{headline_slug}/"
