AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  news-2000 SAM config

Globals:
  Function:
    Timeout: 10
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'www.2000.news'"
    Domain:
      DomainName: api.2000.news
      CertificateArn: arn:aws:acm:us-east-2:663940524453:certificate/a9364e96-df7e-4471-8c2b-fd484e557c7b
      SecurityPolicy: TLS_1_2
      EndpointConfiguration: REGIONAL

Resources:

  Stories:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Stories
      AttributeDefinitions:
        - AttributeName: YearMonthDay
          AttributeType: S
        - AttributeName: Title
          AttributeType: S
      KeySchema:
        - AttributeName: YearMonthDay
          KeyType: HASH
        - AttributeName: Title
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Words:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Words
      AttributeDefinitions:
        - AttributeName: WordType
          AttributeType: S
        - AttributeName: Word
          AttributeType: S
      KeySchema:
        - AttributeName: WordType
          KeyType: HASH
        - AttributeName: Word
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Fetch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Fetch/fetch.fetch
      Runtime: python3.9
      MemorySize: 1024
      Environment:
        Variables:
          NEWS_DATA_API_KEY: xxx
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Enabled: True
          
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Stories

  Subvert:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Subvert/subvert.subvert
      Runtime: python3.9
      MemorySize: 1024
      Timeout: 60
      Environment:
        Variables:
          OPENAI_API_KEY: xxx
      Events:
       DDBEvent:
         Type: DynamoDB
         Properties:
           Stream: !GetAtt Stories.StreamArn
           StartingPosition: TRIM_HORIZON
           BatchSize: 3
           Enabled: True
          
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Stories
        - DynamoDBCrudPolicy:
            TableName: !Ref Words

  Get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Get/get.get
      Runtime: python3.9
      MemorySize: 1024
      Environment:
        Variables:
          SUBVERSION_RATE: 0.8
      Events:
        GetApiEvent:
          Type: Api
          Properties:
            Path: /stories
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Stories
        - DynamoDBCrudPolicy:
            TableName: !Ref Words

Outputs:
  GetStoriesApi:
    Description: "Custom API Gateway endpoint for prod GetStories"
    Value: "https://api.2000.news/stories"
